### ISSUE TITLE
module 'networkx' has no attribute 'write_gpickle'

### ISSUE THREAD

**Issue by theharshith** [Manas02/molecularnetwork#9]
hey

not able to find the write_gpickle for the sample code. 

error msg:

``` in save_graph
    networkx.write_gpickle(self.graph, f"{graphname}.gpickle")
AttributeError: module 'networkx' has no attribute 'write_gpickle'
(myenv-lx) harshu@harshith-lx:~/personal/new-str/streamlit_app/dev-ing$ 
```

**Comment by Manas02** [comment]
Indeed this is a packaging issue.
The latest version of [NetworkX](https://networkx.org/documentation/stable/) does not contain [write_gpickle](https://networkx.org/documentation/networkx-1.10/reference/generated/networkx.readwrite.gpickle.write_gpickle.html).
A workaround is to simply use `joblib.dump`
I'll implement this and close this issue ASAP.
Thanks !

**Comment by Manas02** [comment]
fixed with latest update
